server.port=8880
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://server.lan:55432/java_samples
spring.datasource.username=isv
spring.datasource.password=test123
spring.sql.init.schema-locations=classpath:schema.sql
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.springframework.data=DEBUG
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG
logging.org.isv.samples.shortener="DEBUG"
shortener.base-url=http://localhost:${server.port}/shortener
shortener.storage-type=database
