server.port=8880
logging.org.isv.samples.shortener="DEBUG"
spring.profiles.active=database,clickhouse
spring.config.import=optional:application-${spring.profiles.active}.properties
shortener.base-url=http://localhost:${server.port}/shortener
shortener.num-threads=10
