/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.isv.samples.algorithms;


public class App {
    public static void main(String... args) {
        TopKFrequentWords.test();
    }

}

